"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
require("./global.css");
exports.metadata = {
    title: 'Welcome to KeyGenius',
    description: 'Generated by create-nx-workspace'
};
function RootLayout({ children }) {
    return (<html lang="en">
      <body>{children}</body>
    </html>);
}
