name: Deploy NestJS to cPanel

on:
  push:
    branches: [ 'main' ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Sprawdź kod z repozytorium
      - name: Check out the repo
        uses: actions/checkout@v2

      # 2. Zainstaluj Node.js
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16' # lub inna wersja zgodna z Twoim projektem

      # 3. Zainstaluj zależności
      - name: Install dependencies
        run: npm ci

      # 4. Uruchom linter (ESLint)
      - name: Lint code
        run: npm run lint

      # 5. Uruchom formater (Prettier)
      - name: Format code
        run: npm run format

      # 6. Zbuduj aplikację NestJS
      - name: Build
        run: npm run build

      # 7. Wyślij przez FTP gotowy folder "dist"
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist
          server-dir: /public_html/nest-app
          log-level: verbose
          method: ftp
